export interface AlumnoExcel{
    ALUMNO_ID: number,
    RUT: string,
    NOMBRE: string,
    APELLIDOS: string,
    NOMBRE_SOCIAL: string,
    CURSO: string,
    GENERO: string,
    'DIRECCIÓN': string,
    COMUNA: string,
    REGION: string,
    TELEFONO_CONTACTO1: number,
    TELEFONO_CONTACTO2: number,
    EMAIL: string,
    RUT_APODERADO_1: string,
    NOMBRE_APODERADO_1: string,
    APELLIDO_APODERADO_1:string,
    EMAIL_APODERADO_1: string,
    TELEFONO_APODERADO_1: number,
    RUT_APODERADO_2: string,
    NOMBRE_APODERADO_2: string,
    APELLIDO_APODERADO_2: string,
    EMAIL_APODERADO_2: string,
    TELEFONO_APODERADO_2: number,
    'ANTECEDENTES MEDICOS': string
  }